---
title: "Typical diatom assemblages"
author: "Jonathan Jupke"
date: "09.10.2020"
output: pdf_document
---

## RT01 Very large rivers  
Achnanthidium eutrophilum, Achnanthidium minutissimum, Amphora pediculus inariensis Complex, Anomoeoneis sphaerophora, Cocconeis euglypta, Cocconeis pediculus, Cyclotella wuethrichiana, Cymbella excisa, Diatoma vulgaris, Encyonema silesicacum minutum lange bertalotii, Eolimna comperei, Eolimna minima seminulum atomoides, Gomphonema olivaceum olivaceoides, Gomphonema parvulum Complex, Gomphonema pumilum complex, Halamphora montana, Luticola ventriconfusa, Mayamaea permitis, Navicula capitatoradiata, Navicula cryptotenella cryptotenelloides, Navicula gregaria, Navicula margalithii tripunctata, Navicula menisculus antonii, Navicula reichardtiana caterva, Navicula rotunda, Nitzschia dissipata recta Complex, Nitzschia fonticola Complex, Nitzschia inconspicua Complex, Nitzschia palea paleacea, Nitzschia sociabilis, Reimeria sinuata, Reimeria uniseriata, Sellaphora submuralis Complex, Gomphonema, Rhoicosphenia  

## RT02 - Lowland, siliceous, medium-large
Achnanthidium minutissimum, Amphora pediculus inariensis Complex, Brachysira styriaca, Cocconeis euglypta, Cocconeis pediculus, Cocconeis placentula, Conticribra guillardii, Delphineis surirella, Diatoma vulgaris, Discostella complex, Encyonema silesicacum minutum lange bertalotii, Entomoneis paludosa, Eolimna minima seminulum atomoides, Eunotia subarcuatoides, Eunotia subtilissima, Fallacia subhamulata helensis, Gomphonema parvulum Complex, Gomphonema saprophilum, Halamphora montana, Mayamaea permitis, Melosira varians Complex, Navicula capitatoradiata, Navicula cryptotenella cryptotenelloides, Navicula gregaria, Navicula lanceolata complex, Navicula margalithii tripunctata, Navicula menisculus antonii, Navicula reichardtiana caterva, Neidium dubium Complex, Nitzschia amphibia Complex, Nitzschia angustiforaminata, Nitzschia dissipata recta Complex, Nitzschia fonticola Complex, Nitzschia labella, Nitzschia palea paleacea, Nitzschia pura linearis Complex, Nitzschia sociabilis, Nitzschia subcapitellata, Pinnularia divergens complex, Plagiogramma laeve, Planothidium lanceolatum, Rhaphoneis amphiceros, Sellaphora submuralis Complex, Skeletonema subsalsum, Thalassiosira bramaputrae, Thalassiosira proschkinae, Rhoicosphenia

## RT03 - Lowland siliceous, very small-small
Achnanthidium minutissimum, Amphora pediculus inariensis Complex, Campylosira cymbelliformis, Cocconeis placentula, Cyclostephanos Complex, Cyclostephanos tholiformis, Cyclotella hakanssoniae, Cyclotella meneghiniana, Dimeregramma minor, Discostella complex, Encyonema triangulum, Eolimna minima seminulum atomoides, Fallacia crassicostata, Gomphonema parvulum Complex, Gomphonema pumilum complex, Halamphora coffeaeformis, Halamphora montana, Melosira varians Complex, Navicula cryptotenella cryptotenelloides, Navicula gottlandica, Navicula gregaria, Navicula lanceolata complex, Navicula margalithii tripunctata, Nitzschia amphibia Complex, Nitzschia dissipata recta Complex, Nitzschia inconspicua Complex, Nitzschia lacuum alpina bryophila  , Nitzschia palea paleacea, Nitzschia perspicua, Nitzschia pura linearis Complex, Nitzschia sociabilis, Planothidium lanceolatum, Platessa bahlsii, Rossithidium linearis, Staurosira punctiformis, Stephanodiscus hantzschii, Surirella brebissonii, Thalassiosira decipiens, Rhoicosphenia

## RT04 - Lowland calcareous, medium-large
Achnanthidium minutissimum, Amphora ocellata, Amphora pediculus inariensis Complex, Caloneis bacillum Complex, Cocconeis euglypta, Cocconeis pediculus, Cocconeis placentula, Cyclotella striata, Encyonema silesicacum minutum lange bertalotii, Eolimna minima seminulum atomoides, Gomphonema hebridense, Gomphonema olivaceum olivaceoides, Gomphonema parvulum Complex, Halamphora montana, Navicula capitatoradiata, Navicula cryptotenella cryptotenelloides, Navicula margalithii tripunctata, Navicula menisculus antonii, Navicula reichardtiana caterva, Nitzschia amphibia Complex, Nitzschia dissipata recta Complex, Nitzschia fonticola Complex, Nitzschia palea paleacea, Nitzschia sociabilis, Planothidium lanceolatum, Stephanodiscus niagarae complex, Thalassiosira gessneri

## RT05 - Lowland calcareous, very small-small
Achnanthes coarctata, Achnanthidium lauenburgianum, Achnanthidium minutissimum, Amphora pediculus inariensis Complex, Caloneis bacillum Complex, Cocconeis euglypta, Cocconeis placentula, Encyonema silesicacum minutum lange bertalotii, Eolimna minima seminulum atomoides, Fallacia subhamulata helensis, Gomphonema dichotomum, Gomphonema parvulum Complex, Gomphonema pumilum complex, Halamphora montana, Hantzschia abundans, Mayamaea Complex, Melosira varians Complex, Navicula cryptocephala, Navicula cryptotenella cryptotenelloides, Navicula gregaria, Navicula margalithii tripunctata, Navicula menisculus antonii, Navicula reichardtiana caterva, Neidiomorpha binodeformis, Neidium iridis Complex, Nitzschia dissipata recta Complex, Nitzschia palea paleacea, Nitzschia sociabilis, Planothidium lanceolatum, Reimeria sinuata, Tabellaria fenestrata Complex, Rhoicosphenia

## RT06 - Lowland, organic and siliceous, very small-large
Achnanthes rupestoides kryophila broenlundense, Achnanthidium minutissimum, Aneumastus stroesei, Cavinula scutelloides pseudoscutiformis, Diatoma anceps, Encyonema silesicacum minutum lange bertalotii, Eunotia  exigua elegans Complex, Eunotia arcus mucophila bilunaris Complex, Eunotia Complex, Eunotia implicata Complex, Eunotia incisa Complex, Eunotia parallela Complex, Eunotia pectinalis Complex, Eunotia septentrionalis, Fragilaria capucina complex, Frustulia rhomboides Complex, Gomphonema angustatum Complex, Gomphonema parvulum Complex, Humidophila schmassmannii, Karayevia amoena nitidiformis, Meridion circulare Complex, Navicula cryptocephala, Navicula rhynchocephala, Nitzschia dissipata recta Complex, Nitzschia flexa, Nitzschia palea paleacea, Nitzschia perminuta Complex, Nitzschia pura linearis Complex, Odontidium mesodon, Pinnularia appenticulata perirrorata silvatica, Pinnularia interrupta Complex, Pinnularia mesolepta Complex, Pinnularia sinistra, Pinnularia subcapitata Complex, Pinnularia viridis complex, Planothidium lanceolatum, Platessa oblongella, Psammothidium curtissimum, Psammothidium helveticum chlidanos daonense, Psammothidium subatomoides, Psammothidium ventrale Complex, Rossithidium petersennii, Rossithidium pusillum anastasiae, Stauroneis complex small, Stauroneis phoenicenteron Complex, Tabellaria flocculosa Complex, Ulnaria ulna complex

## RT08 - Mid-altitude, siliceous, medium-large
Achnanthidium minutissimum, Amphora pediculus inariensis Complex, Cocconeis euglypta, Cocconeis placentula, Encyonema silesicacum minutum lange bertalotii, Eolimna minima seminulum atomoides, Gomphoneis eriense, Gomphonema bavaricum, Gomphonema parvulum Complex, Gomphonema pumilum complex, Humidophila perpusilla, Mayamaea alcimonica, Mayamaea permitis, Melosira varians Complex, Navicula cryptotenella cryptotenelloides, Navicula gregaria, Navicula lanceolata complex, Navicula margalithii tripunctata, Navicula reichardtiana caterva, Nitzschia costei, Nitzschia dissipata recta Complex, Nitzschia fonticola Complex, Nitzschia inconspicua Complex, Nitzschia palea paleacea, Planothidium lanceolatum, Reimeria sinuata, Sellaphora submuralis Complex, Rhoicosphenia

## RT09 - Mid-altitude siliceous, very small-small
Achnanthidium minutissimum, Amphora micra, Amphora pediculus inariensis Complex, Chamaepinnularia submuscicola, Cocconeis euglypta, Cocconeis placentula, Encyonema silesicacum minutum lange bertalotii, Eolimna minima seminulum atomoides, Eolimna neocaledonica, Fragilaria heidenii, Gomphonema parvulum Complex, Navicula cryptocephala, Navicula cryptotenella cryptotenelloides, Navicula gregaria, Navicula lanceolata complex, Navicula venezuelensis, Naviculadicta cosmopolitana, Nitzschia dissipata recta Complex, Nitzschia frequens, Nitzschia inducta, Nitzschia palea paleacea, Nitzschia valdecostata, Planothidium lanceolatum, Reimeria sinuata, Tabellaria quadriseptata Complex

## RT12 – Mid-altitude, organic and siliceous 
Achnanthidium linearioide, Achnanthidium minutissimum, Brachysira neoexilis, Brachysira zellensis, Caloneis tenuis Complex, Cavinula scutelloides pseudoscutiformis, Chamaepinnularia begeri mediocris, Diatoma mesodon, Discostella complex, Encyonema gaeumannii perpusillum, Encyonema gracile luna, Encyonema silesicacum minutum lange bertalotii, Encyonopsis descripta falaisensis microcephala, Eucocconeis laevis alpestris, Eunotia  exigua elegans Complex, Eunotia arcus mucophila bilunaris Complex, Eunotia implicata Complex, Eunotia incisa Complex, Eunotia naegelii, Eunotia pectinalis Complex, Eunotia praerupta Complex, Fragilaria arcus, Fragilaria capucina complex, Fragilaria construens pseudoconstruens, Fragilaria tenera complex, Frustulia rhomboides Complex, Gomphonema acuminatum Complex, Gomphonema parvulum Complex, Lindavia rossii complex, Navicula angusta, Navicula notha leptostriata, Neidium affine Complex, Nitzschia bavarica Complex, Nitzschia perminuta Complex, Pinnularia subcapitata Complex, Planothidium lanceolatum, Psammothidium marginulatum scoticum lacus vulcani levenderi, Psammothidium rossii altaica, Psammothidium ventrale Complex, Rossithidium nodosum, Rossithidium pusillum anastasiae, Tabellaria flocculosa Complex, Ulnaria ulna complex, Stenopterobia

## RT16 – Glacial Rivers 
Achnanthidium atomoides, Achnanthidium minutissimum, Achnanthidium subatomus, Amphora pediculus inariensis Complex, Cocconeis euglypta, Cocconeis placentula, Cocconeis pseudolineata, Cymbella tridentina, Diadesmis gallica, Diatoma moniliformis tenuis, Distrionella incognita, Encyonema silesicacum minutum lange bertalotii, Fragilaria incognita, Fragilaria virescens complex, Gomphonema olivaceum olivaceoides, Gomphonema parvulum Complex, Gomphonema pumilum complex, Navicula cryptotenella cryptotenelloides, Navicula margalithii tripunctata, Nitzschia dissipata recta Complex, Nitzschia fonticola Complex, Odontidium hyemale, Reimeria sinuata

## RT17 - Mediterranean, lowland, medium-Large, perennial
Achnanthidium minutissimum, Amphora pediculus inariensis Complex, Aneumastus tusculus, Brachysira garrensis, Cocconeis euglypta, Cocconeis pediculus, Cocconeis placentula, Cymbella excisa, Cymbella kappii, Diatoma vulgaris, Encyonema silesicacum minutum lange bertalotii, Encyonema simile, Eolimna minima seminulum atomoides, Fallacia muraloides, Gomphonema parvulum Complex, Gomphonema pumilum complex, Luticola kotschyi, Navicula cryptotenella cryptotenelloides, Navicula margalithii tripunctata, Navicula reichardtiana caterva, Nitzschia dissipata recta Complex, Nitzschia fonticola Complex, Nitzschia inconspicua Complex, Nitzschia palea paleacea, Planothidium holstii, Planothidium reichardtii, Pseudostaurosira neoelliptica

## RT18 - Mediterranean, mid altitude, medium-large, perennial
Achnanthidium minutissimum, Amphora pediculus inariensis Complex, Cocconeis pediculus, Cocconeis placentula, Cosmioneis pusilla, Cymbella excisa, Diatoma moniliformis tenuis, Encyonema silesicacum minutum lange bertalotii, Encyonopsis descripta falaisensis microcephala, Gomphonema olivaceum olivaceoides, Gomphonema parvulum Complex, Gomphonema pumilum complex, Halamphora thumensis, Navicula cryptotenella cryptotenelloides, Navicula margalithii tripunctata, Navicula reichardtiana caterva, Nitzschia dissipata recta Complex, Nitzschia fonticola Complex, Pinnularia alpina lata borealis complex, Reimeria sinuata, Gomphonema

## RT19 - Mediterranean, very small-small, perennial
Achnanthidium minutissimum, Amphora pediculus inariensis Complex, Cocconeis euglypta, Cocconeis pediculus, Cocconeis placentula, Cymbella excisa, Cymbella tumidula, Encyonema geisslerae, Encyonema silesicacum minutum lange bertalotii, Eolimna minima seminulum atomoides, Epithemia goeppertiana, Epithemia turgida, Gomphonema pumilum complex, Gomphonema rosenstockianum, Navicula cryptotenella cryptotenelloides, Navicula margalithii tripunctata, Nitzschia dissipata recta Complex, Nitzschia fonticola Complex, Stauroneis separanda
