---
title: "Typical macroinvertebrate assemblages"
author: "Jonathan Jupke"
date: "20.11.2020"
output: pdf_document
---

## RT1    
Borysthenia naticina, Obesogammarus obesus, Ancylus, Baetis, Caenis, Chelicorophium, Corbicula, Corophium, Dikerogammarus, Dina, Dreissena, Ecnomus, Ephoron, Ferrissia, Gammarus, Hydropsyche, Jaera, Leptocerus, Lithoglyphus, Musculium, Neureclipsis, Orconectes, Plea, Potamopyrgus, Sisyra, Chironomidae, Mysidae  

## RT2    
Peregriana peregra, Serratella ignita, Ancylus, Baetis, Caenis, Ecdyonurus, Elmis, Gammarus, Hydropsyche, Leuctra, Limnius, Pisidium, Polycentropus, Potamopyrgus, Rhithrogena, Rhyacophila, Chironomidae, Limnephilidae, Lumbricidae, Naididae, Simuliidae   

## RT3    
Alainites muticus, Peregriana peregra, Serratella ignita, Ancylus, Baetis, Dicranota, Ecdyonurus, Elmis, Gammarus, Hydropsyche, Leuctra, Limnius, Oulimnius, Pisidium, Polycentropus, Protonemura, Rhithrogena, Rhyacophila, Stictochironomus, Velia, Baetidae, Chironomidae, Elmidae, Limnephilidae, Naididae, Odontoceridae, Ptychopteridae, Simuliidae  

## RT4    
Armiger crista, Peregriana peregra, Serratella ignita, Ancylus, Anodonta, Asellus, Baetis, Caenis, Cladotanytarsus, Clinotanypus, Corynoneura, Crangonyx, Cryptochironomus, Dicrotendipes, Elmis, Endochironomus, Erpobdella, Gammarus, Glossiphonia, Glyptotendipes, Hemiclepsis, Hydropsyche, Laccophilus, Limnius, Molanna, Nebrioporus, Oulimnius, Pisidium, Potamopyrgus, Sphaerium, Synorthocladius, Theromyzon, Bithyniidae, Chironomidae, Crangonyctidae, Molannidae, Naididae, Neritidae, Unionidae    

## RT5    
Peregriana labiata, Agabus, Ancylus, Baetis, Elmis, Gammarus, Helophorus, Hydroporus, Hydropsyche, Hygrotus, Hyphydrus, Limnius, Noterus, Pisidium, Potamopyrgus, Chironomidae, Limnephilidae   

## RT8    
Serratella ignita, Ancylus, Baetis, Dicranota, Ecdyonurus, Elmis, Esolus, Gammarus, Hydraena, Hydropsyche, Isoperla, Leuctra, Limnius, Pedicia, Protonemura, Rhithrogena, Rhyacophila, Chironomidae, Limnephilidae, Limoniidae, Sericostomatidae, Simuliidae  

## RT9    
Ameletus inopinatus, Serratella ignita, Amphinemura, Baetis, Dicranota, Elmis, Gammarus, Hydraena, Hydropsyche, Isoperla, Leuctra, Limnius, Protonemura, Rhithrogena, Rhyacophila, Chironomidae, Limnephilidae, Sericostomatidae, Simuliidae  

## RT10    
Propappus volki, Serratella ignita, Ancylus, Baetis, Conchapelopia, Ecdyonurus, Elmis, Esolus, Gammarus, Hydraena, Hydropsyche, Hydroptila, Leuctra, Limnius, Rhithrogena, Rhyacophila, Riolus, Torleya, Chironomidae, Limnephilidae, Limoniidae, Oligochaeta, Simuliidae 
  
## RT11    
Baetis, Ecdyonurus, Elmis, Ephemera, Esolus, Gammarus, Hydraena, Hydropsyche, Leuctra, Limnius, Odontocerum, Protonemura, Rhithrogena, Rhyacophila, Riolus, Chironomidae, Limnephilidae, Limoniidae, Oligochaeta, Sericostomatidae, Simuliidae  

## RT14    
Baetis, Ephemerella, Gordiacea, Heptagenia, Hydraenida, Hydropsyche, Leuctra, Odontocera, Rhithrogena, Rhyacophila, Athericidae, Chironomidae, Culicidae, Dolichopodidae, Empididae, Helophorida, Limnephilidae, Limoniidae, Oligochaeta, Perlidae, Sciomyzidae, Sericostomatidae, Simuliidae 
  
## RT15    
Baetis, Ecdyonurus, Elmis, Gammarus, Hydraena, Hydropsyche, Isoperla, Leuctra, Limnius, Protonemura, Rhithrogena, Rhyacophila, Chironomidae, Empididae, Limnephilidae, Limoniidae, Oligochaeta, Simuliidae  
  
## RT16    
Agriotypus, Ancylus, Baetis, Ecdyonurus, Elmis, Epeorus, Hydraena, Hydropsyche, Isoperla, Leuctra, Limnius, Nemoura, Odontocerum, Parametriocnemus, Perlodes, Protonemura, Rhithrogena, Rhyacophila, Chironomidae, Empididae, Limnephilidae, Limoniidae, Oligochaeta, Simuliidae     
 
## RT18    
Baetis, Boyeria, Caenis, Calopteryx, Chimarra, Choroterpes, Dryops, Ecdyonurus, Elmis, Ephemerella, Esolus, Gammarus, Hydropsyche, Hydroptila, Leuctra, Limnius, Metalype, Normandia, Oligoneuriella, Onychogomphus, Orthotrichia, Potamopyrgus, Pseudocentroptilum, Rhyacophila, Setodes, Chironomidae, Empididae, Gomphidae, Limoniidae, Naucoridae, Oligochaeta, Simuliidae    
   
