---
title: "Typical macro-invertebrate assemblages"
author: "Jonathan Jupke"
date: "16.11.2020"
output: pdf_document
---

## RT 1 Very Large Rivers 
### Typical Assemblage 
Ancylus, Baetis, Caenis, Chelicorophium, Corbicula, Dikerogammarus, Echinogammarus, Gammarus, Hydropsyche, Jaera, Potamopyrgus, Chironomidae

### Specific Taxa
Atyaephyra, Chelicorophium, Corbicula, Dikerogammarus, Dreissena, Echinogammarus, Ecnomus, Ephoron, Jaera, Lithoglyphus, Potamanthus

## RT 2_3 
### Typical Assemblage 
Peregriana peregra, Serratella ignita, Ancylus, Baetis, Caenis, Dicranota, Ecdyonurus, Elmis, Esolus, Gammarus, Hydropsyche, Isoperla, Lepidostoma, Leuctra, Limnius, Oulimnius, Pisidium, Polycentropus, Potamopyrgus, Protonemura, Rhithrogena, Rhyacophila, Baetidae, Chironomidae, Elmidae, Heptageniidae, Hydropsychidae, Limnephilidae, Lumbricidae, Naididae, Simuliidae

### Specific Taxa
Hydraenidae, Lepidostomatidae, Odontoceridae

## RT 4_5
### Typical Assemblage
Peregriana peregra, Serratella ignita, Ancylus, Asellus, Baetis, Caenis, Elmis, Erpobdella, Gammarus, Glossiphonia, Hydropsyche, Limnius, Micropsectra, Oulimnius, Pisidium, Potamopyrgus, Sphaerium, Chironomidae, Naididae

### Specific Taxa
Cladotanytarsus, Clinotanypus, Crangonyx, Endochironomus, Graptodytes, Hemiclepsis, Hygrotus, Molanna, Notonecta, Physa, Stictotarsus, Theromyzon, Bithyniidae, Crangonyctidae, Neritidae, Valvatidae

## RT8-11_15_16
### Typical Assemblage
Serratella ignita, Ancylus, Baetis, Ecdyonurus, Elmis, Ephemera, Esolus, Gammarus, Hydraena, Hydropsyche, Isoperla, Leuctra, Limnius, Odontocerum, Protonemura, Rhithrogena, Rhyacophila, Riolus, Chironomidae, Limnephilidae, Limoniidae, Oligochaeta, Sericostomatidae, Simuliidae

### Specific Taxa
None 

## RT 12
### Typical Assemblage
Ameletus inopinatus, Nigrobaetis niger, Amphinemura, Baetis, Dicranota, Elmis, Ephemerella, Heptagenia, Hydraena, Isoperla, Lepidostoma, Leptophlebia, Leuctra, Oulimnius, Polycentropus, Protonemura, Rhyacophila, Chironomidae, Empididae, Simuliidae

### Specific Taxa
Ameletus inopinatus

## RT 14
### Typical Assemblage
Baetis, Ecdyonurus, Ephemerella, Heptagenia, Hydraena, Hydraenida, Hydropsyche, Leuctra, Protonemura, Rhithrogena, Rhyacophila, Athericidae, Chironomidae, Empididae, Limnephilidae, Limoniidae, Oligochaeta, Perlidae, Sericostomatidae, Simuliidae

### Specific Taxa
Hydraenida, Nepidae, Rhagionidae

## RT 18
### Typical Assemblage
Ancylus, Baetis, Caenis, Calopteryx, Ecdyonurus, Elmis, Ephemerella, Esolus, Gammarus, Hydropsyche, Hydroptila, Leuctra, Limnius, Onychogomphus, Oulimnius, Polycentropus, Potamopyrgus, Psychomyia, Rhyacophila, Riolus, Ceratopogonidae, Chironomidae, Empididae, Limoniidae, Oligochaeta, Simuliidae, Tabanidae

### Specific Taxa
Acentrella, Boyeria, Chimarra, Helichus, Oligoneuriella, Pseudocentroptilum, Gomphidae, Naucoridae

