---
title: "Typical diatom assemblages"
author: "Jonathan Jupke"
date: "20.11.2020"
output: pdf_document
---

## RT1_2_4    

Achnanthidium eutrophilum, Achnanthidium minutissimum, Amphora pediculus inariensis Complex, Caloneis bacillum Complex, Cocconeis euglypta, Cocconeis pediculus, Cocconeis placentula, Cyclotella costei, Cyclotella meneghiniana, Cymbella excisa, Diatoma vulgaris, Encyonema silesicacum minutum lange bertalotii, Eolimna comperei, Eolimna minima seminulum atomoides, Fallacia subhamulata helensis, Fragilaria capucina complex, Gomphonema olivaceum olivaceoides, Gomphonema parvulum Complex, Gomphonema pumilum complex, Halamphora montana, Melosira varians Complex, Navicula capitatoradiata, Navicula cryptotenella cryptotenelloides, Navicula gregaria, Navicula lanceolata complex, Navicula margalithii tripunctata, Navicula menisculus antonii, Navicula reichardtiana caterva, Nitzschia amphibia Complex, Nitzschia dissipata recta Complex, Nitzschia fonticola Complex, Nitzschia inconspicua Complex, Nitzschia palea paleacea, Nitzschia sociabilis, Planothidium lanceolatum, Reimeria sinuata, Reimeria uniseriata, Sellaphora submuralis Complex, Surirella brebissonii, Ulnaria ulna complex, Gomphonema, Mayamaea, Rhoicosphenia    

## RT3    
Achnanthidium minutissimum, Amphora pediculus inariensis Complex, Asterionella formosa, Aulacoseira ambigua, Bacillaria paxillifera, Berkeleya rutilans, Cocconeis euglypta, Cocconeis placentula, Cyclotella atomus, Cyclotella meneghiniana, Encyonema silesicacum minutum lange bertalotii, Eolimna minima seminulum atomoides, Eolimna rhombelliptica, Eunotia implicata Complex, Fallacia crassicostata, Fragilaria capucina complex, Frustulia rhomboides Complex, Gomphonema parvulum Complex, Gomphonema pumilum complex, Gomphosphenia lingulatiformis, Halamphora montana, Hippodonta capitata, Hippodonta pseudacceptata, Humidophila contenta, Lindavia rossii complex, Melosira varians Complex, Navicula arvensis difficillima  , Navicula cryptocephala, Navicula cryptotenella cryptotenelloides, Navicula gottlandica, Navicula gregaria, Navicula lanceolata complex, Navicula margalithii tripunctata, Navicula menisculus antonii, Navicula rhynchocephala, Navicula schroeteri, Navicula tenelloides salinicola incertata  , Navicula ventralis medioconvexa  , Nitzschia amphibia Complex, Nitzschia aurariae, Nitzschia dissipata recta Complex, Nitzschia draveillensis, Nitzschia fonticola Complex, Nitzschia frustulum Complex, Nitzschia fruticosa, Nitzschia inconspicua Complex, Nitzschia lacuum alpina bryophila  , Nitzschia palea paleacea, Nitzschia pura linearis Complex, Nitzschia sociabilis, Nitzschia tubicola, Pinnularia microstauron Complex, Planothidium delicatulum, Planothidium lanceolatum, Reimeria sinuata, Sellaphora submuralis Complex, Staurosira venter, Stephanodiscus hantzschii, Stephanodiscus neoastraea, Surirella brebissonii, Ulnaria ulna complex, Cyclostephanos, Discostella, Mayamaea, Parlibellus, Placoneis, Rhoicosphenia  

## RT5    
Achnanthidium lauenburgianum, Achnanthidium minutissimum, Amphora indistincta, Amphora pediculus inariensis Complex, Caloneis bacillum Complex, Caloneis lancettula, Cocconeis euglypta, Cocconeis pediculus, Cocconeis placentula, Cyclotella meneghiniana, Cymatopleura elliptica, Encyonema reichardtii, Encyonema silesicacum minutum lange bertalotii, Eolimna minima seminulum atomoides, Fallacia insociabilis complex, Fallacia pygmaea forcipata, Fallacia subhamulata helensis, Gomphonema olivaceum olivaceoides, Gomphonema parvulum Complex, Gomphonema pumilum complex, Halamphora montana, Kolbesia gessneri, Melosira varians Complex, Navicula capitatoradiata, Navicula cryptocephala, Navicula cryptotenella cryptotenelloides, Navicula gregaria, Navicula margalithii tripunctata, Navicula menisculus antonii, Navicula reichardtiana caterva, Nitzschia dissipata recta Complex, Nitzschia palea paleacea, Nitzschia pura linearis Complex, Nitzschia sigma Complex, Nitzschia sociabilis, Planothidium lanceolatum, Reimeria sinuata, Surirella brebissonii, Surirella lacrimula, Surirella suecica, Ulnaria ulna complex, Diploneis, Gomphonema, Gyrosigma, Mayamaea, Rhoicosphenia   

## RT8    
Achnanthidium deflexum Complex, Achnanthidium minutissimum, Achnanthidium subhudsonis, Amphora pediculus inariensis Complex, Cocconeis euglypta, Cocconeis pediculus, Cocconeis placentula, Cocconeis pseudolineata, Diatoma vulgaris, Encyonema silesicacum minutum lange bertalotii, Eolimna minima seminulum atomoides, Fragilaria capucina complex, Geissleria ignota complex, Gomphonema olivaceum olivaceoides, Gomphonema parvulum Complex, Gomphonema pumilum complex, Melosira varians Complex, Navicula capitatoradiata, Navicula cryptocephala, Navicula cryptotenella cryptotenelloides, Navicula gregaria, Navicula lanceolata complex, Navicula margalithii tripunctata, Navicula menisculus antonii, Navicula reichardtiana caterva, Nitzschia costei, Nitzschia dissipata recta Complex, Nitzschia fonticola Complex, Nitzschia inconspicua Complex, Nitzschia palea paleacea, Nitzschia pura linearis Complex, Nitzschia sociabilis, Planothidium lanceolatum, Reimeria sinuata, Sellaphora submuralis Complex, Ulnaria ulna complex, Fistulifera, Gomphonema, Mayamaea, Rhoicosphenia  

## RT9    
Achnanthidium deflexum Complex, Achnanthidium minutissimum, Achnanthidium subatomus, Achnanthidium subhudsonis, Amphora pediculus inariensis Complex, Cocconeis euglypta, Cocconeis placentula, Cocconeis pseudolineata, Diatoma mesodon, Encyonema silesicacum minutum lange bertalotii, Eolimna minima seminulum atomoides, Fragilaria capucina complex, Fragilaria tenera complex, Gomphonema parvulum Complex, Gomphonema pumilum complex, Melosira varians Complex, Navicula cryptocephala, Navicula cryptotenella cryptotenelloides, Navicula gregaria, Navicula gregarioides, Navicula lanceolata complex, Navicula lapsa, Navicula margalithii tripunctata, Navicula reichardtiana caterva, Navicula rhynchocephala, Nitzschia dissipata recta Complex, Nitzschia fonticola Complex, Nitzschia inconspicua Complex, Nitzschia palea paleacea, Nitzschia pura linearis Complex, Nupela lapidosa, Planothidium lanceolatum, Psammothidium helveticum chlidanos daonense, Psammothidium subatomoides, Reimeria sinuata, Ulnaria ulna complex, Mayamaea, Rhoicosphenia 

## RT16   
Achnanthidium atomoides, Achnanthidium minutissimum, Achnanthidium subatomus, Amphora pediculus inariensis Complex, Cocconeis euglypta, Cocconeis placentula, Cocconeis pseudolineata, Diatoma ehrenbergii, Diatoma moniliformis tenuis, Encyonema silesicacum minutum lange bertalotii, Eolimna minima seminulum atomoides, Fragilaria arcus, Fragilaria austriaca, Fragilaria capucina complex, Fragilaria virescens complex, Geissleria ignota complex, Gomphonema olivaceum olivaceoides, Gomphonema parvulum Complex, Gomphonema pumilum complex, Navicula cryptotenella cryptotenelloides, Navicula gregaria, Navicula margalithii tripunctata, Navicula reichardtiana caterva, Nitzschia dissipata recta Complex, Nitzschia fonticola Complex, Nitzschia inconspicua Complex, Nitzschia palea paleacea, Planothidium lanceolatum, Reimeria sinuata, Gomphonema, Mayamaea  

## RT17_18    
Achnanthidium eutrophilum, Achnanthidium minutissimum, Amphora pediculus inariensis Complex, Cocconeis euglypta, Cocconeis pediculus, Cocconeis placentula, Cymbella excisa, Denticula tenuis, Diatoma moniliformis tenuis, Diatoma vulgaris, Encyonema silesicacum minutum lange bertalotii, Encyonopsis descripta falaisensis microcephala, Eolimna minima seminulum atomoides, Fragilaria capucina complex, Fragilaria virescens complex, Gomphonema olivaceum olivaceoides, Gomphonema parvulum Complex, Gomphonema pumilum complex, Melosira varians Complex, Navicula capitatoradiata, Navicula cryptotenella cryptotenelloides, Navicula margalithii tripunctata, Navicula menisculus antonii, Navicula reichardtiana caterva, Nitzschia dissipata recta Complex, Nitzschia fonticola Complex, Nitzschia inconspicua Complex, Nitzschia palea paleacea, Planothidium lanceolatum, Reimeria sinuata, Ulnaria ulna complex, Gomphonema, Mayamaea, Rhoicosphenia    

## RT19    
Achnanthidium deflexum Complex, Achnanthidium minutissimum, Amphora pediculus inariensis Complex, Brachysira neoexilis, Cocconeis euglypta, Cocconeis pediculus, Cocconeis placentula, Cocconeis pseudolineata, Cymbella excisa, Denticula tenuis, Encyonema silesicacum minutum lange bertalotii, Encyonopsis cesatii, Eolimna minima seminulum atomoides, Eucocconeis laevis alpestris, Fragilaria capucina complex, Fragilaria tenera complex, Gomphonema olivaceum olivaceoides, Gomphonema parvulum Complex, Gomphonema pumilum complex, Melosira varians Complex, Navicula cryptotenella cryptotenelloides, Navicula margalithii tripunctata, Navicula menisculus antonii, Navicula reichardtiana caterva, Nitzschia dissipata recta Complex, Nitzschia fonticola Complex, Nitzschia inconspicua Complex, Nitzschia palea paleacea, Planothidium lanceolatum, Reimeria sinuata, Ulnaria ulna complex, Cymbopleura, Gomphonema, Rhoicosphenia    

  

  

 

  
  
