---
title: "Seasonal typical macro-invertebrate assemblages"
author: "Jonathan Jupke"
date: "27.11.2020"
output: pdf_document
---

## RT10 spring 
Baetis, Dicranota, Elmis, Gammarus, Hydropsyche, Leuctra, Rhithrogena, Rhyacophila, Chironomidae, Limnephilidae, Simuliidae    

## RT10 summer 
Baetis, Elmis, Esolus, Gammarus, Hydropsyche, Hydroptila, Leuctra, Limnius, Rhyacophila, Riolus, Athericidae, Chironomidae, Empididae, Limnephilidae, Limoniidae, Simuliidae    

## RT10 autumn 
Ancylus, Baetis, Calopteryx, Ecdyonurus, Elmis, Ephemera, Esolus, Gammarus, Hydraena, Hydropsyche, Hydroptila, Leuctra, Limnius, Pisidium, Potamopyrgus, Rhithrogena, Rhyacophila, Riolus, Chironomidae, Limoniidae, Simuliidae

## RT10 winter 
Baetis, Ecdyonurus, Epeorus, Gammarus, Hydropsyche, Leuctra, Rhithrogena, Rhyacophila, Chironomidae, Limnephilidae, Limoniidae, Simuliidae    
 
## RT16 summer 
Baetis, Ecdyonurus, Echinogammarus, Elmis, Ephemerella, Esolus, Gammarus, Hydraena, Hydropsyche, Leuctra, Protonemura, Rhithrogena, Rhyacophila, Anthomyiidae, Athericidae, Blephariceridae, Chironomidae, Dytiscidae, Empididae, Ephydridae, Glossiphoniidae, Hydropsychidae, Limnephilidae, Limoniidae, Simuliidae, Sphaeriidae    

## RT16 autumn 
Acentrella, Baetis, Ecdyonurus, Epeorus, Hydropsyche, Isoperla, Leuctra, Nemoura, Rhithrogena, Rhyacophila, Riolus, Chironomidae, Empididae, Limnephilidae, Limoniidae, Simuliidae, Tipulidae  

## RT16 winter 
Baetis, Ecdyonurus, Isoperla, Leuctra, Rhithrogena, Rhyacophila, Chironomidae, Empididae, Limnephilidae, Limoniidae, Simuliidae    
